--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: categoria; Type: TABLE; Schema: public; Owner: bigdatanow; Tablespace: 
--

CREATE TABLE categoria (
    source text NOT NULL,
    canal text,
    medio_id numeric NOT NULL,
    activo boolean,
    last date,
    std text
);


ALTER TABLE public.categoria OWNER TO bigdatanow;

--
-- Data for Name: categoria; Type: TABLE DATA; Schema: public; Owner: bigdatanow
--

COPY categoria (source, canal, medio_id, activo, last, std) FROM stdin;
http://www.elpopular.com.ar/rss/	Todo	29	t	2016-12-07	\N
http://tn.com.ar/rss.xml	TN Hoy	9	t	2016-12-07	\N
http://www.lmneuquen.com.ar/rss/RSS.Ultimo.Momento.xml	Últimas noticias	41	t	2015-10-07	\N
http://www.ambito.com/rss/suplementos.asp?s=Ambito%20del%20Placer	Suplemento Ambito del Placer	10	t	2016-08-05	\N
http://www.infonews.com/rss/politica.xml	Política	17	\N	2016-05-02	\N
http://www.elsigloweb.com/rss.php	Todo	54	t	2016-01-31	\N
http://www.ambito.com/rss/noticias.asp?s=Espect%E1culos	Espectáculos	10	t	2016-12-07	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=12	Política	82	t	2016-12-07	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=14	Internacional	82	t	2016-07-06	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=13	Economía	82	t	2016-11-13	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=15	Mundo Obrero	82	t	2016-12-02	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=20	Sociedad	82	t	2016-11-16	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=17	Géneros y Sexualidades	82	t	2016-09-20	\N
http://feeds.feedburner.com/diariolavozdezarate/tVZY	Todo	47	t	2016-12-07	\N
http://laverdadonline.webnode.com/rss/novedades.xml	Novedades	44	t	2015-01-29	\N
http://www.perfil.com/rss/economia.xml	Economía	16	t	2016-07-31	\N
http://www.elancasti.com.ar/rss/feed.html?r=53	Especiales	46	t	2016-11-27	\N
http://www.elliberal.com.ar/Economia.xml	Economía	33	t	2016-02-10	\N
http://www.ellitoral.com/rss/econ.xml	Economía	35	t	2016-12-06	\N
http://www.lacapital.com.ar/rss/laregion.xml	Region	18	t	2016-05-04	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=4	Política	49	t	2016-12-07	\N
http://www.eltribuno.info/rss/salta/salta.xml	Salta	24	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=70	Cultura	53	t	2016-12-07	\N
http://www.ambito.com/rss/suplementos.asp?s=Comercio%20Exterior	Suplemento Comercio Exterior	10	t	\N	\N
http://www.diariouno.com.ar/servicios/rss/masleidas.xml	Más leídas	19	f	2015-02-05	\N
http://www.diariosanrafael.com.ar/secciones-fijas/aniversario?format=feed	Aniversario	75	t	2016-10-14	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=187	Medios	82	t	2016-07-06	\N
http://www.losandes.com.ar/rss/sup-economia	Sup. Economía	20	t	2016-12-04	\N
http://laopinionpergamino.com.ar/?format=feed&type=rss	Todo	52	t	2015-01-29	\N
http://www.telam.com.ar/rss2/espectaculos.xml	espectáculos	8	t	2016-12-07	\N
http://mundod.lavoz.com.ar/taxonomy/term/2/feed	Tenis	5	t	2016-09-30	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6734	adncultura	4	t	2015-07-03	\N
http://www.telam.com.ar/rss2/cultura.xml	cultura	8	t	2016-12-06	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=4	Mundo	12	f	2015-02-03	\N
http://www.apfdigital.com.ar/xml.asp	Todo	79	t	2016-11-29	\N
http://www.pagina12.com.ar/diario/rss/no.xml	no	6	t	2016-11-10	\N
http://www.losandes.com.ar/rss/aniversario	Aniversario	20	t	2016-10-21	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=25	Interés General	79	t	2016-09-26	\N
http://www.continental.com.ar/feed.aspx?id=INICIO	Todo	7	t	2016-12-07	\N
http://www.ellitoral.com/rss/depo.xml	Deportes	35	t	2016-12-06	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=5	Deportes	48	t	2016-12-07	\N
http://www.losandes.com.ar/rss	Últimas noticias	20	t	2016-12-07	\N
http://www.ambito.com/rss/noticiasp.asp	Principales Noticias	10	t	2016-12-07	\N
http://www.ciudad.com.ar/secciones/espectaculos-0/feed	Espectáculos	76	f	2015-05-11	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=16	Juventud	82	t	2016-07-06	\N
http://wp.unosantafe.com.ar/servicios/rss/tecnologia.xml	Tecnología	32	f	2015-01-27	\N
http://www.diarionorte.com/rss/feed/	Todo	38	t	2016-12-07	\N
http://www.larazon.com.ar/rss/	Todo	34	t	2016-12-07	\N
http://tn.com.ar/feed/politica	política	9	t	2015-10-21	\N
http://www.losandes.com.ar/rss/salud	Salud	20	t	2016-11-08	\N
http://www.clarin.com/rss/internet/	internet	2	t	2015-02-02	\N
http://tn.com.ar/feed/musica	La Viola	9	t	2015-10-21	\N
http://www.ratingcero.com/rss/tv0.xml	TV0	31	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=1	Ciudad	12	f	2015-02-03	\N
http://www.lapoliticaonline.com/files/rss/energia.xml	Energía	21	t	2016-12-06	\N
http://www.clarin.com/rss/mundo/	mundo	2	t	2016-12-07	\N
http://www.diariobae.com/feed	Todo	50	t	2016-04-26	\N
http://www.losandes.com.ar/rss/mele	MELE	20	t	\N	\N
http://www.diariouno.com.ar/servicios/rss/canal-extreme.xml	Canal extreme	19	f	2015-01-27	\N
http://www.clarin.com/rss/ciudades/	ciudades	2	t	2016-12-07	\N
http://www.lanueva.com/news/rss/category/5	Mundo	22	t	2016-12-07	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9542	Editorial	23	t	2016-04-30	\N
http://www.lacapital.com.ar/rss/elmundo.xml	Mundo	18	t	2016-05-04	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=7	Espectáculos	12	f	2015-02-03	\N
http://www.minutouno.com/rss/economia.xml	Economía	15	t	2016-12-07	\N
http://www.diariouno.com.ar/servicios/rss/canal-autos.xml	Canal autos	19	f	2015-02-06	\N
http://www.lanueva.com/news/rss/category/29	Canal DxT	22	t	2015-05-20	\N
http://www.lanueva.com/news/rss/category/7	Deportes	22	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=501	CUBO	12	f	2015-01-16	\N
http://www.eldiarioargentino.com/ResourcesManager.aspx?Resource=Rss.aspx&Rss=18	Economía	78	t	2016-08-15	\N
http://wp.unosantafe.com.ar/servicios/rss/santafe.xml	Provincia	32	f	2015-01-27	\N
http://mundod.lavoz.com.ar/rss.xml	Mundo D	5	t	2016-09-30	\N
http://www.diariosanrafael.com.ar/salud?format=feed	Salud	75	t	2016-12-06	\N
http://www.clarin.com/rss/sociedad/	sociedad	2	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/component/k2/itemlist?format=feed&moduleID=88	Últimas noticias	75	t	2016-07-09	\N
http://www.diariouno.com.ar/servicios/rss/policiales.xml	Policiales	19	t	2016-01-06	\N
http://vos.lavoz.com.ar/rss.xml	Vos	5	t	2016-09-30	\N
http://www.ellitoral.com/rss/area.xml	Locales	35	t	2016-12-06	\N
http://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=m&output=rss	Salud	80	t	2016-12-07	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=1	Provinciales	79	t	2016-11-29	\N
http://www.lapoliticaonline.com/files/rss/politica.xml	Política	21	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=4	Espectáculo	46	t	2016-12-06	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/economia.xml	Economía	13	t	2016-05-26	\N
http://www.ellitoral.com/rss/regi.xml	Región	35	t	2016-12-06	\N
http://www.clarin.com/rss/politica/	política	2	t	2016-12-07	\N
http://www.lmneuquen.com.ar/rss/RSS.Regionales.xml	Región	41	t	2015-10-07	\N
http://www.tribunadigital.com.ar/feed/	Todo	55	t	2016-12-07	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=21	Primera Plana	79	t	2016-11-29	\N
http://www.pagina12.com.ar/diario/rss/ultimas_noticias.xml	últimas noticias	6	t	2016-11-13	\N
http://www.perfil.com/rss/politica.xml	Política	16	t	2016-08-01	\N
http://www.lapoliticaonline.com/files/rss/judiciales.xml	Judiciales	21	t	2016-12-07	\N
http://www.minutouno.com/rss/negocios.xml	Negocios	15	t	2015-03-17	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=28	opinión	4	t	2016-12-07	\N
http://www.nuevodiadigital.com/index.php/feed/index.rss	Todo	65	t	2016-12-07	\N
http://www.losandes.com.ar/rss/internacionales	Internacionales	20	t	2016-02-17	\N
http://www.ambito.com/rss/suplementos.asp?s=Ambito%20Municipal	Suplemento Ambito Municipal	10	t	2016-11-24	\N
http://www.losandes.com.ar/rss/mas-deportes	Más Deportes	20	t	2016-12-07	\N
http://www.infonews.com/rss/economia.xml	Economía	17	\N	2016-05-02	\N
http://www.diariopanorama.com/ultimomomento.xml	Últimas noticias	26	f	2015-06-03	\N
http://www.minutouno.com/rss/entretenimiento.xml	Entretenimiento	15	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/origen=1	títulos ed. impresa	4	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=28	Salud	53	t	\N	\N
http://www.diariosanrafael.com.ar/secciones-fijas/protagonismo?format=feed	Protagonismo	75	t	2016-12-06	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=3	Policiales	79	t	2016-11-29	\N
http://wp.unosantafe.com.ar/servicios/rss/espectaculos.xml	Espectáculos	32	f	2015-01-27	\N
http://www.elancasti.com.ar/rss/feed.html?r=8	Educación	46	t	2015-06-23	\N
http://www.lanueva.com/news/rss/category/30	Canal tu espacio	22	t	2016-10-04	\N
http://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=h&output=rss	Ciencia y Tecnología	80	t	2016-12-07	\N
http://www.laizquierdadiario.com/spip.php?page=backend_portada	Notas Destacadas	82	t	2016-07-07	\N
http://www.telam.com.ar/rss2/opinion.xml	opinión	8	t	2016-12-07	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=7	Vida	37	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/nuestra-gente?format=feed	Nuestra gente	75	t	2016-12-06	\N
http://www.elancasti.com.ar/rss/feed.html?r=52	Entrevistas	46	t	2016-11-30	\N
http://mundod.lavoz.com.ar/taxonomy/term/3/feed	Fútbol	5	t	2016-09-30	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=57	Periodista Ciudadano	37	t	2015-07-14	\N
http://www.ambito.com/rss/suplementos.asp?s=Panorama%20Automotor	Suplemento Panorama Automotor	10	t	2016-08-16	\N
http://www.pagina12.com.ar/diario/rss/las12.xml	las 12	6	t	2016-11-11	\N
http://www.lanueva.com/news/rss/category/8	Aplausos	22	t	2016-12-07	\N
http://feedproxy.google.com/LADD-infogeneral	Locales - Información General	66	t	2016-12-07	\N
http://www.losandes.com.ar/rss/beca-a-calle	Beca A. Calle	20	t	2015-11-11	\N
http://www.minutouno.com/rss/deportes.xml	Deportes	15	t	2015-03-17	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=18	Cultura	82	t	2016-12-04	\N
http://www.lmneuquen.com.ar/rss/RSS.Policiales.xml	Policiales	41	t	2015-10-07	\N
http://feedproxy.google.com/LADD-nacionales	Nacionales e Internacionales	66	t	2016-11-26	\N
http://www.telam.com.ar/rss2/turismo.xml	turismo	8	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/economia?format=feed	Economía	75	t	2016-10-06	\N
http://www.buenosairesherald.com/articles/rss.aspx	Todo	1	t	2016-12-04	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=8	Actualidad	49	t	2016-12-07	\N
http://www.losandes.com.ar/rss/economia	Economía	20	t	2016-12-07	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=258	PTS	82	t	2016-07-06	\N
http://www.elliberal.com.ar/Santiago.xml	Santiago	33	t	2016-02-10	\N
http://www.ellitoral.com/rss/tapa.xml	Titulares de Tapa	35	t	\N	\N
http://www.ellitoral.com/rss/soci.xml	Escenarios y sociedad	35	t	2016-12-06	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=432	tecnología	4	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=31	Fin de Semana	53	t	\N	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=7	Mundo	49	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=504	suplemento turismo	4	t	2016-12-07	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/deportes.xml	Deportes	13	t	2016-06-05	\N
http://www.pregon.com.ar/_rss/destacadas.xml	Todo	56	t	2015-07-22	\N
http://www.lacapital.com.ar/rss/senales.xml	Señales	18	t	2015-03-15	\N
http://www.ratingcero.com/rss/lenguadetrapo.xml	Lengua de Trapo	31	t	\N	\N
https://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=e&output=rss	Espectáculos	80	t	2016-12-07	\N
http://www.eleco.com.ar/rss/1/poltica.xml	Política	36	f	2015-03-26	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=25	Septimo día	12	f	2015-02-01	\N
http://www.lanueva.com/news/rss/category/66	Mundial Brasil 2014	22	t	2015-03-27	\N
http://www.pagina12.com.ar/diario/rss/cash.xml	economía	6	t	2016-05-20	\N
http://www.lmneuquen.com.ar/rss/RSS.Exterior.xml	Internacionales	41	t	2015-10-07	\N
http://www.bhi.com.ar/feed	Todo	73	t	2015-02-01	\N
http://www.eltribuno.info/rss/salta/masleidas.xml	Más leídas	24	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=73	Quebrachitos	53	t	2016-12-07	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=2	Sociedad	48	t	2016-12-07	\N
http://www.ratingcero.com/rss/personajes.xml	Personajes	31	t	2016-12-07	\N
https://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=b&output=rss	Economía	80	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1348	suplemento countries	4	t	\N	\N
http://www.lacapital.com.ar/rss/canal-salud.xml	Canal Salud	18	t	2015-01-27	\N
http://www.lacapital.com.ar/rss/opinion.xml	Opinión	18	t	2016-04-25	\N
http://wp.unosantafe.com.ar/servicios/rss/deportes.xml	Deportes	32	f	2015-01-27	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=120	espectáculos	4	t	2016-12-07	\N
http://www.eldia.com/mc/clasi_rss.aspx?idr=15	Festejos y guarderías	12	f	2015-01-16	\N
http://www.ratingcero.com/rss/xquesiyxqueno.xml	X qué sí y x qué no	31	t	2016-07-18	\N
http://www.ambito.com/rss/suplementos.asp?s=Viernes	Suplemento Viernes	10	t	2015-03-25	\N
http://www.ellitoral.com/rss/um.xml	Últimas noticias	35	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=2	País	46	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=30	política	4	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/portada-papel?format=feed	Portada Papel	75	t	2016-12-06	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7774	buenos aires	4	t	2016-12-07	\N
http://www.lanueva.com/news/rss/category/9	Opinión	22	t	2016-11-04	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=4	Provinciales	37	t	2016-12-06	\N
http://www.laizquierdadiario.com/spip.php?page=backend&id_mot=23	Deportes	82	t	2016-07-06	\N
http://www.diariosanrafael.com.ar/actualidad?format=feed	Actualidad	75	t	2016-12-07	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=8	Turismo	48	t	2016-12-07	\N
https://news.google.com/news?cf=all&ned=es_ar&hl=es&topic=el&output=rss	Elecciones	80	t	\N	\N
http://www.infonews.com/rss/deportes.xml	Deportes	17	\N	2016-05-02	\N
http://www.lacapital.com.ar/rss/policiales.xml	Policiales	18	t	2016-05-04	\N
http://canchallena.feedsportal.com/rss	Todo	25	t	2016-04-15	\N
http://www.lacapital.com.ar/rss/cartasdelectores.xml	Cartas de lectores	18	t	2016-04-25	\N
http://www.ellitoral.com/rss/opin.xml	Opinión	35	t	2016-12-06	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/espectaculos.xml	Espectáculos	13	t	2016-06-03	\N
http://www.diariosanrafael.com.ar/actualidad/itemlist?format=feed&moduleID=133	Más leídas	75	t	2016-12-07	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=8	Policiales	37	t	2016-12-07	\N
http://www.lacapital.com.ar/rss/escenario.xml	Escenario	18	t	2016-05-04	\N
http://www.elancasti.com.ar/rss/feed.html?r=3	Mundo	46	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=6	Policiales	53	t	2016-12-07	\N
http://www.losandes.com.ar/rss/mundo-club-house	Mundo Club House	20	t	2016-12-07	\N
http://www.ellitoral.com/rss/info.xml	General	35	t	2016-12-05	\N
http://www.elcolonodeloeste.com.ar/rss/noticias.xml	Todo	68	t	2016-12-06	\N
http://www.perfil.com/rss/ultimomomento.xml	Ultimas Noticias	16	t	2016-08-01	\N
http://www.elancasti.com.ar/rss/feed.html?r=60	Moda y Belleza	46	t	2016-08-03	\N
http://www.eltribuno.info/rss/salta/home.xml	El tribuno	24	t	2016-12-07	\N
http://www.diariouno.com.ar/servicios/rss/deportes.xml	Deportes	19	f	2015-01-27	\N
http://www.lapoliticaonline.com/files/rss/santafe.xml	Santa Fe	21	t	2016-12-02	\N
http://www.eleco.com.ar/rss/4/inters_general.xml	General	36	f	2015-03-26	\N
http://www.ambito.com/rss/suplementos.asp?s=Prestigio%20y%20Poder	Suplemento Prestigio y Poder	10	t	2015-01-28	\N
http://www.ambito.com/rss/noticias.asp?s=Pol%EDtica	Política	10	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/editorial?format=feed	Editorial	75	t	2016-12-06	\N
http://www.elliberal.com.ar/Opinion.xml	Opinión	33	t	2016-02-07	\N
http://www.laopinionaustral.com.ar/rss.asp	Todo	57	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=9	Sociedad	46	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=8	Deportes	12	f	2015-02-03	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=2	Provincia	12	f	2015-02-03	\N
http://www.pagina12.com.ar/diario/rss/libros.xml	libros	6	t	2016-11-13	\N
http://www.diariouno.com.ar/servicios/rss/ultimas-lepra.xml	Ultimas de la Lepra	19	f	2015-02-03	\N
http://www.diariosanrafael.com.ar/secciones-fijas/video-del-dia?format=feed	Vídeo del día	75	t	2016-12-07	\N
http://www.ellitoral.com/rss/med.xml	Medio Ambiente	35	t	2016-11-25	\N
http://ole.feedsportal.com/c/33068/f/577712/index.rss	Todo	14	t	2015-09-08	\N
http://www.lmneuquen.com.ar/rss/RSS.Espectaculos.xml	Espectáculos	41	t	2015-10-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=20	DECO	12	f	2015-02-02	\N
http://www.diariosanrafael.com.ar/secciones-fijas/fallecimientos?format=feed	Fallecimientos	75	t	2016-12-02	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=3	Regionales	37	t	2016-12-04	\N
http://www.lacapital.com.ar/rss/masleidas.xml	Más leídas 	18	t	2016-05-04	\N
http://www.losandes.com.ar/rss/vendimia	Vendimia	20	t	2016-02-17	\N
http://www.ciudad.com.ar/secciones/bla-bla-bla/feed	Bla bla bla	76	f	2015-05-08	\N
http://personajes.lanacion.com.ar/herramientas/rss	Personajes	4	t	2015-09-10	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=4	Nacionales	79	t	2016-11-29	\N
http://www.lanueva.com/news/rss/category/32	Canal C291	22	t	2016-09-20	\N
http://mundod.lavoz.com.ar/taxonomy/term/5617/feed	Y más	5	t	2016-09-30	\N
http://www.telam.com.ar/rss2/politica.xml	política	8	t	2016-12-07	\N
http://www.pagina12.com.ar/diario/rss/libero.xml	libero	6	t	2016-11-15	\N
http://www.diariosanrafael.com.ar/policiales?format=feed	Policiales	75	t	2016-12-07	\N
http://www.ambito.com/rss/noticias.asp?s=Informaci%F3n%20General	Información General	10	t	2016-12-07	\N
http://www.diariouno.com.ar/servicios/rss/canal-mujer.xml	Canal Mujer	19	f	2015-02-06	\N
http://www.diariosanrafael.com.ar/sociedad?format=feed	Sociedad	75	t	2016-12-07	\N
http://www.cronista.com/rss.html	Ultimo momento	11	t	2016-12-07	\N
http://feedproxy.google.com/LADD-policiales	Locales - Policiales - Sociedad	66	t	2016-12-07	\N
http://www.pagina12.com.ar/diario/rss/m2.xml	m2	6	t	2016-11-12	\N
http://www.eldia.com/mc/clasi_rss.aspx?idr=2	Alquiler de inmuebles	12	f	2015-01-16	\N
http://www.diariosanrafael.com.ar/secciones-fijas/ceschi?format=feed	Ceschi	75	t	2016-12-06	\N
http://www.lacapital.com.ar/rss/politica.xml	Política	18	t	2016-05-04	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=3	Internacionales	53	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=6	Policiales	46	t	2016-12-07	\N
http://www.telam.com.ar/rss2/economia.xml	economía	8	t	2016-12-07	\N
http://feedproxy.google.com/LADD-deportes	Locales - Deportes	66	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=10	Información General	12	f	2015-02-03	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9532	País	23	t	2016-05-01	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9574	Sociedad	23	t	2016-05-01	\N
http://www.elancasti.com.ar/rss/feed.html?r=65	Revista Express	46	t	\N	\N
http://www.lacapital.com.ar/rss/salud.xml	Salud	18	t	2015-10-07	\N
http://www.perfil.com/rss/internacional.xml	Internacional	16	t	2016-07-31	\N
http://www.eldia.com/.rss	Todo	12	t	2016-11-29	\N
http://www.perfil.com/rss/policia.xml	Policiales	16	t	2016-07-31	\N
http://www.elsol.com.ar/portada.rss	Todo	43	t	2016-12-07	\N
http://tn.com.ar/feed/internacional	Internacional	9	t	2015-10-21	\N
http://tn.com.ar/feed/show	Show	9	t	2015-10-21	\N
http://www.diariouno.com.ar/servicios/rss/ultimas-tomba.xml	Ultimas del Tomba	19	f	2015-02-05	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9528	Tecnología	23	t	2016-04-27	\N
http://tn.com.ar/feed/sociedad	Sociedad	9	t	2015-10-21	\N
http://www.diariosanrafael.com.ar/el-pais?format=feed	País	75	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1312	suplemento moda y belleza	4	t	2016-12-03	\N
http://www.diariosanrafael.com.ar/secciones-fijas/comunicados?format=feed	Comunicados	75	t	2016-12-06	\N
http://www.diariouno.com.ar/servicios/rss/espectaculos.xml	Espectaculos	19	f	2015-02-05	\N
http://www.pagina12.com.ar/diario/rss/soy.xml	soy	6	t	2016-11-11	\N
http://www.diariosanrafael.com.ar/secciones-fijas/que-mundo?format=feed	Que mundo	75	t	2016-12-06	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1363	suplemento inmuebles comerciales	4	t	2016-10-10	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=131	deportes	4	t	2016-12-07	\N
http://www.lacapital.com.ar/rss/informaciongral.xml	Información General	18	t	2016-05-04	\N
http://www.paralelo32.com.ar/rss/index.php	Todo	58	t	2016-11-09	\N
http://www.ambito.com/rss/noticias.asp?s=Internacionales	Internacionales	10	t	2016-10-12	\N
http://www.pagina12.com.ar/diario/rss/turismo.xml	turismo	6	t	2016-11-13	\N
http://www.lapoliticaonline.com/files/rss/transporte.xml	Transporte	21	t	2016-12-07	\N
http://tn.com.ar/feed/tecnologia	tecnología	9	t	2015-04-08	\N
http://www.laizquierdadiario.com/spip.php?page=backend_tv	RSS La Izquierda Diario TV	82	t	2016-07-06	\N
http://www.diariosanrafael.com.ar/secciones-fijas/bella?format=feed	Bella	75	t	2016-12-05	\N
http://feedproxy.google.com/LADD-todo	Todo	66	t	2016-12-07	\N
http://www.minutouno.com/rss/espectaculos.xml	Espectáculos	15	t	2016-12-07	\N
http://www.clarin.com/rss/ieco/	economía	2	t	2016-11-29	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=1344	suplemento comunidad	4	t	2016-12-05	\N
http://www.clarin.com/rss/deportes/	deportes	2	t	2016-12-07	\N
http://wp.unosantafe.com.ar/servicios/rss/a_fondo.xml	A fondo	32	f	2015-01-27	\N
http://www.ciudad.com.ar/secciones/que-look/feed	Qué Look!	76	f	2015-05-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=23	Pesca	12	f	2015-01-29	\N
http://feedproxy.google.com/LADD-horoscopos	Horóscopos de la semana	66	t	2016-12-04	\N
http://www.diaadia.com.ar/rss.xml	Todo	28	t	2016-12-07	\N
http://feedproxy.google.com/LADD-politica	Locales - Política y Economía	66	t	2016-12-07	\N
http://www.elliberal.com.ar/Interior.xml	Interior	33	t	2016-02-10	\N
http://www.cronista.com/rss.html\n	Todo	11	t	\N	\N
http://www.eleco.com.ar/rss/7/sociales.xml	Sociales	36	f	2015-03-26	\N
http://www.eldiarioargentino.com/ResourcesManager.aspx?Resource=Rss.aspx&Rss=17	Política	78	t	2016-10-17	\N
http://www.diariodecuyo.com.ar/rss/	Todo	27	t	2015-06-24	\N
http://www.eldia.com/mc/clasi_rss.aspx?idr=4	Compra y venta de inmuebles	12	f	2015-01-16	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=6	Opinión	49	t	2016-12-07	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=6	Nacionales	37	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=62	Tecno	46	t	2016-08-03	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=1	Opinión	53	t	2016-08-03	\N
http://www.diariouno.com.ar/servicios/rss/canal-bebes.xml	Canal bebés	19	f	\N	\N
http://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=s&output=rss	Deportes	80	t	2016-12-07	\N
http://www.elliberal.com.ar/Policiales.xml	Policiales	33	t	2016-02-10	\N
http://www.perfil.com/rss/tecnologia.xml	Tecnología	16	t	2016-07-31	\N
http://www.lanueva.com/news/rss/category/2	Punta Alta	22	t	2016-11-30	\N
http://www.telam.com.ar/rss2/mundo.xml	mundo	8	t	2016-09-20	\N
http://www.lacapital.com.ar/rss/estilo.xml	Estilo	18	t	\N	\N
http://www.lanueva.com/news/rss/category/28	Canal Blog colectivo	22	t	2016-10-03	\N
https://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=n&output=rss	Nacional	80	t	2016-12-07	\N
http://www.losandes.com.ar/rss/sociales	Sociales	20	t	2016-12-05	\N
http://www.pagina12.com.ar/diario/rss/rosario.xml	rosario	6	t	2016-11-15	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=9	Deportes	49	t	2016-12-07	\N
http://www.diariouno.com.ar/servicios/rss/pais.xml	País	19	t	2016-01-06	\N
https://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=t&output=rss	Ciencia y Tecnología	80	t	2016-12-07	\N
http://www.eldia.com/mc/clasi_rss.aspx?idr=7	Automotores	12	f	2015-01-16	\N
http://www.lapoliticaonline.com/files/rss/economia.xml	Economía	21	t	2016-12-06	\N
http://contenidos.lanacion.com.ar/herramientas/rss/origen=2	últimas noticias	4	t	2016-12-07	\N
http://www.losandes.com.ar/rss/los-andes-con-vos-videos	Los Andes con Vos: Videos	20	t	\N	\N
http://wp.unosantafe.com.ar/servicios/rss/portada.xml	Portada	32	f	2015-01-27	\N
http://www.perfil.com/rss/espectaculos.xml	Espectáculos	16	t	2016-07-31	\N
http://www.infonews.com/rss/espectaculos.xml	Espectaculos	17	\N	2016-05-02	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=494	revista la nacion	4	t	2016-12-04	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=27	Turísmo	53	t	\N	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=3	Provincial	48	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=71	Política	53	t	2016-12-07	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=5	Internacionales	79	t	2016-11-29	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=12	Municipales	79	t	2016-11-29	\N
http://wp.unosantafe.com.ar/servicios/rss/mundo.xml	Mundo	32	f	2015-01-27	\N
http://www.lmneuquen.com.ar/rss/RSS.Deportes.xml	Deportes	41	t	2015-10-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=63	Tendencias	46	t	2016-08-03	\N
http://edimpresa.unoentrerios.com.ar/rss/	Todo	30	f	2015-01-27	\N
http://www.lanueva.com/news/rss/category/3	Región	22	t	2016-12-07	\N
http://www.perspectivasur.com/archivos/rss/ultimas_noticias_1.xml	Todo	63	t	2016-12-07	\N
http://www.diariouno.com.ar/servicios/rss/tecnologia.xml	tecnología	19	f	2015-02-05	\N
http://wp.unosantafe.com.ar/servicios/rss/policiales.xml	Policiales	32	f	2015-01-27	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/sociedad.xml	Sociedad	13	t	2016-05-24	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/tecno.xml	Tecnología	13	t	2016-06-03	\N
http://www.lapoliticaonline.com/files/rss/mendoza.xml	Mendoza	21	t	2016-12-06	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7	el mundo	4	t	2016-12-07	\N
http://www.lapoliticaonline.com/files/rss/ciudad.xml	Ciudad	21	t	2016-12-07	\N
http://www.telam.com.ar/rss2/tecnologia.xml	tecnología	8	t	2016-12-07	\N
http://www.pagina12.com.ar/diario/rss/principal.xml	principal	6	t	2016-11-15	\N
http://www.pagina12.com.ar/diario/rss/radar.xml	radar	6	t	2016-11-13	\N
http://www.losandes.com.ar/rss/sup-cultura	Sup. Cultura	20	t	2016-12-03	\N
http://www.diariosanrafael.com.ar/politica?format=feed	Política	75	t	2016-08-15	\N
http://www.lacapital.com.ar/rss/educacion.xml	Educación	18	t	2016-04-30	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=500	Mujer	12	f	2015-01-23	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7775	seguridad	4	t	2016-12-07	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=24	Personajes	37	t	2016-12-04	\N
http://www.telam.com.ar/rss2/ultimasnoticas.xml	últimas noticias	8	t	2016-01-25	\N
http://www.periodicolea.com/rss/noticias.xml	Todo	64	t	2015-07-16	\N
http://www.elliberal.com.ar/LaBanda.xml	La banda	33	t	2016-02-10	\N
http://laverdadonline.webnode.com/rss/all.xml	Todo	44	t	2015-01-29	\N
http://www.elancasti.com.ar/rss/feed.html?r=5	Deportes	46	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=347	suplemento comercio exterior	4	t	2016-12-01	\N
http://www.eleco.com.ar/rss/0/portada.xml	Tapa	36	f	2015-03-26	\N
http://www.minutouno.com/rss/politica.xml	Política	15	t	2016-12-07	\N
http://www.losandes.com.ar/rss/politica	Política	20	t	2016-12-07	\N
http://www.perfil.com/rss/columnistas.xml	Opinión	16	t	2016-07-31	\N
http://www.ratingcero.com/rss/mediaticos.xml	Mediáticos	31	t	2016-04-11	\N
http://www.losandes.com.ar/rss/los-andes-con-vos-fotos	Los Andes con Vos: Fotos	20	t	\N	\N
http://www.eldiarioargentino.com/ResourcesManager.aspx?Resource=Rss.aspx&Rss=19	Deportes	78	t	2016-10-17	\N
http://feedproxy.google.com/LADD-espectaculos	Locales - Espectáculos	66	t	2016-12-06	\N
http://www.clarin.com/rss/multimedia/	multimedia	2	t	2015-10-19	\N
http://news.google.com/news?pz=1&cf=all&ned=es_ar&hl=es&topic=w&output=rss	Internacional	80	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=6373	the wall street journal americas	4	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=5	Deportes	53	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=72	Información General	53	t	2016-12-07	\N
http://www.losandes.com.ar/rss/rumbos	Rumbos	20	t	2016-12-07	\N
http://www.perfil.com/rss/salud.xml	Salud	16	t	2016-07-26	\N
http://www.pagina12.com.ar/diario/rss/futuro.xml	futuro	6	t	2014-11-11	\N
http://www.infonews.com/rss/sociedad.xml	Sociedad	17	\N	2016-05-02	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=53285	Bariloche	23	t	2016-05-01	\N
http://www.diariouno.com.ar/servicios/rss/portada.xml	Portada	19	t	2016-01-06	\N
http://www.losandes.com.ar/rss/sociedad	Sociedad	20	t	2016-12-07	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=421	suplemento enfoques	4	t	2015-07-05	\N
http://www.ciudad.com.ar/galerias/feed/diosas	Diosas	76	f	2015-02-03	\N
http://mundod.lavoz.com.ar/taxonomy/term/1/feed	Básquet	5	t	2016-09-30	\N
http://www.ambito.com/rss/noticias.asp?s=Econom%EDa	Economía	10	t	2016-12-07	\N
http://www.losandes.com.ar/rss/policiales	Policiales	20	t	2016-12-07	\N
http://www.losandes.com.ar/rss/editorial	Editorial	20	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=64	Hogar y Deco	46	t	2016-05-10	\N
http://www.ambito.com/rss/noticias.asp?s=Deportes	Deportes	10	t	2016-12-07	\N
http://www.diarioeltiempo.com.ar/feed	Todo	40	t	2016-12-07	\N
http://www.lanueva.com/news/rss/category/4	País	22	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/secciones-fijas/hace-diez-anos?format=feed	Hace 10 años	75	t	2016-12-04	\N
http://www.lacapital.com.ar/rss/home.xml	Portada	18	t	2016-12-07	\N
http://www.lmcordoba.com.ar/rss/ultimas.php	Últimas noticias	42	t	2016-05-25	\N
http://www.eldiarioargentino.com/ResourcesManager.aspx?Resource=Rss.aspx&Rss=16	General	78	t	2016-10-17	\N
http://www.elancasti.com.ar/rss/feed.html?r=1	Política y Economía	46	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=24	Revista domingo	12	f	2015-02-01	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=23	Por los barrios	37	t	2016-12-02	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=2	Política	79	t	2016-11-27	\N
http://www.diariosanrafael.com.ar/deportes?format=feed	Deportes	75	t	2016-12-07	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=2	Nacionales	53	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=42	Rugby	12	f	2015-01-16	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=22	Moda	12	f	2015-01-29	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9525	Policiales	23	t	2016-05-01	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9862	Municipales	23	t	2016-04-30	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9529	Salud	23	t	2016-04-28	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9533	Mundo	23	t	2016-05-01	\N
http://tn.com.ar/feed/policiales	policiales	9	t	2015-10-21	\N
http://tn.com.ar/feed/deportes	deportes	9	t	2015-10-21	\N
http://www.pagina12.com.ar/diario/rss/espectaculos.xml	espectaculos	6	t	2016-05-20	\N
http://www.lanueva.com/news/rss/category/10	Sociedad	22	t	2016-12-07	\N
http://www.minutouno.com/rss/principal.xml	Principales Noticias	15	t	2016-12-07	\N
http://www.elancasti.com.ar/rss/feed.html?r=51	Cultura	46	t	2016-12-07	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/ahora.xml	Ahora	13	t	2016-06-05	\N
http://www.diarioprimeralinea.com.ar/rss/feed.html?r=69	Cuadrito	53	t	2015-08-23	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=337	suplemento el campo	4	t	2016-12-07	\N
http://www.elliberal.com.ar/Politica.xml	Política	33	t	2016-02-10	\N
http://www.ellitoral.com/rss/poli.xml	Política	35	t	2016-12-06	\N
http://www.elancasti.com.ar/rss/feed.html?r=61	Destinos	46	t	2016-08-03	\N
http://www.elancasti.com.ar/rss/feed.html?r=7	Opinión	46	t	2016-12-07	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=5	Policiales	12	f	2015-02-03	\N
http://www.losandes.com.ar/rss/especial-fiestas	Especial Fiestas	20	t	2015-12-15	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=371	suplemento al volante	4	t	2016-12-03	\N
http://www.losandes.com.ar/rss/turismo	Turismo	20	t	2016-12-04	\N
http://www.losandes.com.ar/rss/fincas	Fincas	20	t	2016-12-03	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=11	Deportes	37	t	2016-12-07	\N
http://www.minutouno.com/rss/mundo.xml	Mundo	15	t	2016-12-07	\N
http://www.ellitoral.com/rss/inte.xml	Internacionales	35	t	2016-12-06	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=7773	sociedad	4	t	2016-12-07	\N
http://www.eldiariocba.com.ar/rss/portada.xml	Todo	51	t	2015-08-09	\N
http://www.diariouno.com.ar/servicios/rss/mundo.xml	Mundo	19	t	2016-01-06	\N
http://www.lacapital.com.ar/rss/economia.xml	Economía	18	t	2016-05-04	\N
http://www.eleco.com.ar/rss/8/necrolgicas.xml	Necrológicas	36	f	2015-03-26	\N
http://www.eleco.com.ar/rss/3/deportes.xml	Deportes	36	f	2015-03-26	\N
http://www.perfil.com/rss/ciencia.xml	Ciencia	16	t	2016-07-31	\N
http://www.lmneuquen.com.ar/rss/RSS.Nacionales.xml	País	41	t	2015-10-07	\N
http://www.lacapital.com.ar/rss/canal-mujer.xml	Canal Mujer	18	t	2015-01-27	\N
http://www.minutouno.com/rss/sociedad.xml	Sociedad	15	t	2016-12-07	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=9	Opinión	37	t	2016-12-06	\N
http://www.prensalibreonline.com.ar/dblog/feedrss.asp	Todo	62	t	2015-01-30	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=6	Espectáculos	48	t	2016-12-07	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=7	Sucesos	48	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/secciones-fijas/etcetera?format=feed	Etcetera	75	t	2016-12-06	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=2	Locales	37	t	2016-12-07	\N
http://wp.unosantafe.com.ar/servicios/rss/pais.xml	País	32	f	2015-01-27	\N
http://www.lanueva.com/news/rss/category/1	Ciudad	22	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/secciones-fijas/espectaculos?format=feed	Espectáculos	75	t	2016-12-07	\N
http://www.eldiariodelarepublica.com/rss.html	Todo	45	t	2016-12-07	\N
http://www.eltribuno.info/rss/salta/deportes.xml	Deportes	24	t	2016-11-24	\N
http://www.ratingcero.com/rss/estopasa.xml	Esto pasa	31	t	2016-12-07	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=5	Economía	49	t	2016-12-07	\N
http://www.lagaceta.com.ar/rss	Todo	3	t	2016-12-07	\N
http://www.elliberal.com.ar/Mundo.xml	Mundo	33	t	2016-02-10	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=3	País	12	f	2015-02-03	\N
http://www.ratingcero.com/rss/cajaboba.xml	Caja Boba	31	t	2016-10-24	\N
http://www.ambito.com/rss/noticias.asp?s=Agro	Campo	10	t	2016-07-12	\N
http://www.campolitoral.com.ar/estatico/campo.xml	Campolitoral	35	t	2016-12-03	\N
http://www.lacapital.com.ar/rss/canal-tecno.xml	Canal Tecnología	18	t	2015-01-27	\N
http://www.lapoliticaonline.com/files/rss/ultimasnoticias.xml	Últimas noticias	21	t	2016-12-07	\N
http://www.ambito.com/rss/noticias.asp?s=Papa%20Francisco	Papa Francisco	10	t	2016-08-11	\N
http://rss.universia.net/AR/Noticias_AR/ar	Todo	77	t	2015-03-16	\N
http://www.lanueva.com/news/rss/category/6	Seguridad	22	t	2016-12-05	\N
http://mundod.lavoz.com.ar/taxonomy/term/6/feed	Motores	5	t	2016-09-21	\N
http://www.infonews.com/rss/mundo.xml	Mundo	17	\N	2016-05-02	\N
http://www.diariouno.com.ar/servicios/rss/canal-salud.xml	Canal Salud	19	f	2015-01-27	\N
http://contenidos.lanacion.com.ar/herramientas/rss/categoria_id=272	economía	4	t	2016-12-07	\N
http://www.ambito.com/rss/noticias.asp?s=Tecnolog%EDa	Tecnología	10	t	2016-08-24	\N
http://www.lavoz.com.ar/rss.xml	Todo	5	t	2016-11-28	\N
http://www.elojodigital.com/seccion/all/rss	Todo	60	t	2016-12-07	\N
http://www.perfil.com/rss/deportes.xml	Deportes	16	t	2016-08-01	\N
http://www.ambito.com/rss/suplementos.asp?s=Rugby	Suplemento Rugby	10	t	\N	\N
http://www.diariouno.com.ar/servicios/rss/canal-tecno.xml	Canal tecno	19	f	2015-02-06	\N
http://www.diariolamanana.com.ar/feeds/default.aspx	Todo	70	t	2016-12-07	\N
http://www.diariodemocracia.com/servicios/rss.asp?r=88	Especiales	37	t	2016-07-12	\N
http://www.varelaaldia.com.ar/rss.xml	Todo	61	f	2015-02-20	\N
http://www.lacapital.com.ar/rss/ovacion.xml	Ovación	18	t	2016-05-05	\N
http://www.lacapital.com.ar/rss/turismo.xml	Turismo	18	t	2016-03-21	\N
http://www.perfil.com/rss/sociedad.xml	Sociedad	16	t	2016-07-31	\N
http://www.laprensa.com.ar/ResourcesManager.aspx?Resource=Rss.aspx&Rss=10	Espectáculos	49	t	2016-12-02	\N
http://www.diariosanrafael.com.ar/secciones-fijas?format=feed	Secciones	75	t	2016-12-06	\N
http://www.diariosanrafael.com.ar/secciones-fijas/de-politica?format=feed	Política	75	t	2016-12-06	\N
http://www.diariosanrafael.com.ar/la-provincia?format=feed	Provincial	75	t	2016-12-07	\N
http://www.telam.com.ar/rss2/policiales.xml	policiales	8	t	2016-12-06	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9527	Economía	23	t	2016-04-23	\N
http://www.telam.com.ar/rss2/sociedad.xml	sociedad	8	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/secciones-fijas/tecnologia?format=feed	Tecnología	75	t	2016-12-07	\N
http://diariopinion.com.ar/rss/	Todo	74	f	2015-06-15	\N
http://www.ciudad.com.ar/secciones/tecuentoalgo/feed	Te cuento algo	76	f	2015-05-11	\N
http://chequeado.com/feed/	Todo	81	t	2016-11-25	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9536&c=/caduca	Últimas noticias	23	t	2015-09-10	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9522	Deportes	23	t	2016-05-01	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9523	Espectáculos	23	t	2016-04-30	\N
http://www.ellitoral.com/rss/suce.xml	Sucesos	35	t	2016-12-06	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=9701	Región	23	t	2016-05-01	\N
http://www.losandes.com.ar/rss/los-andes-con-vos-gente-que-busca-gente	Los Andes con Vos: Gente que busca gente	20	t	\N	\N
http://www.elliberal.com.ar/Deportivo.xml	Deportes	33	t	2016-02-10	\N
http://www.elheraldo.com.ar/notas_rss.php	Últimas noticias	59	t	2016-05-08	\N
http://www.diariouno.com.ar/servicios/rss/a_fondo.xml	A fondo	19	f	2015-02-05	\N
http://www.diarioextra.com.ar/rss.xml	Todo	71	t	2016-11-29	\N
http://www.telam.com.ar/rss2/deportes.xml	deportes	8	t	2016-12-07	\N
http://www.losandes.com.ar/rss/isha-nos-habla	Isha nos habla	20	t	2016-10-17	\N
http://www.losandes.com.ar/rss/los-andes-con-vos-notas	Los Andes con Vos: Notas	20	t	2015-10-29	\N
http://www.losandes.com.ar/rss/los-andes-con-vos-mascotas	Los Andes con Vos: Mascotas	20	t	2015-05-11	\N
http://www.losandes.com.ar/rss/arquitectura	Arquitectura	20	t	2016-11-30	\N
http://www.losandes.com.ar/rss/mendocinos-por-el-mundo	Mendocinos por el mundo	20	t	2016-04-05	\N
http://www.apfdigital.com.ar/xml.asp?id_Seccion=6	Ciencia y tecnología	79	t	2016-09-10	\N
http://www.losandes.com.ar/rss/escribe-el-lector	Escribe el Lector	20	t	2016-12-07	\N
http://www.losandes.com.ar/rss/mirador	Mirador	20	t	2016-02-17	\N
http://www.losandes.com.ar/rss/opinion	Opinión	20	t	2016-12-07	\N
http://www.losandes.com.ar/rss/estilo	Estilo	20	t	2016-12-07	\N
http://www.losandes.com.ar/rss/departamentales	Departamentales	20	t	2016-02-17	\N
http://www.diariosanrafael.com.ar/notas-de-opinion?format=feed	Notas de opinión	75	t	2016-12-06	\N
http://www.lacapital.com.ar/rss/canal-autos.xml	Canal Autos	18	t	2015-01-27	\N
http://www.minutouno.com/rss/tecnologia.xml	Tecnología	15	t	2016-12-07	\N
http://www.lacapital.com.ar/rss/laciudad.xml	Ciudad	18	t	2016-05-04	\N
http://www.lanueva.com/news/rss/index?last_hour=1	Últimas noticias	22	t	2016-07-23	\N
http://www.diariouno.com.ar/servicios/rss/canal-unokids.xml	Canal UnoKids	19	f	\N	\N
http://www.perfil.com/rss/cultura.xml	cultura	16	t	2016-07-31	\N
http://www.ratingcero.com/rss/ultimasnoticias.xml	Últimas noticias	31	t	2016-12-07	\N
http://www.diariosanrafael.com.ar/el-mundo?format=feed	Mundo	75	t	2016-12-07	\N
http://www.lmneuquen.com.ar/rss/RSS.Opiniones.xml	Opinión	41	t	2015-10-07	\N
http://www.eleco.com.ar/rss/2/policiales.xml	Policiales	36	f	2015-03-26	\N
http://www.lacapital.com.ar/rss/tecnologia.xml	Tecnología	18	t	2015-10-29	\N
http://www.clarin.com/rss/policiales/	policiales	2	t	2016-12-07	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=9	Mundo	48	t	2016-12-07	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=1	Política	48	t	2016-11-22	\N
http://www.lapoliticaonline.com/files/rss/provincia.xml	Provincia	21	t	2016-12-06	\N
http://www.diarionco.net/feed/	Todo	69	t	2016-10-27	\N
http://www.eldiariodecarlospaz.com/rss/feed.html?r=4	Nacionales	48	t	2016-12-07	\N
http://feedproxy.google.com/LADD-sociales	Sociales de LAD	66	t	2016-12-06	\N
http://cdn01.am.infobae.com/adjuntos/163/rss/politica.xml	Política	13	t	2016-05-13	\N
http://www.infonews.com/rss/infonews.xml	Ultimas Noticias	17	\N	2016-05-02	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=21	Joven	12	f	2015-01-30	\N
http://www.elliberal.com.ar/rssimpreso.xml	Impresa	33	t	2016-02-10	\N
http://www.ambito.com/rss/suplementos.asp?s=Ambito%20del%20Campo	Suplemento Ambito del Campo	10	t	2016-11-11	\N
http://www.eldia.com.ar/rss/rss.aspx?ids=34	Zona norte	12	f	2015-01-30	\N
http://www.elheraldo.com.ar/locales_rss.php	Locales	59	t	2016-05-07	\N
http://www.rionegro.com.ar/diario/funciones/xml/rss.aspx?idcat=60621	Viedma	23	t	2016-05-01	\N
\.


--
-- Name: categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: bigdatanow; Tablespace: 
--

ALTER TABLE ONLY categoria
    ADD CONSTRAINT categoria_pkey PRIMARY KEY (source);


--
-- Name: categoria_medio_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: bigdatanow
--

ALTER TABLE ONLY categoria
    ADD CONSTRAINT categoria_medio_id_fkey FOREIGN KEY (medio_id) REFERENCES medios(id);


--
-- Name: categoria; Type: ACL; Schema: public; Owner: bigdatanow
--

REVOKE ALL ON TABLE categoria FROM PUBLIC;
REVOKE ALL ON TABLE categoria FROM bigdatanow;
GRANT ALL ON TABLE categoria TO bigdatanow;
GRANT SELECT ON TABLE categoria TO PUBLIC;


--
-- PostgreSQL database dump complete
--

