server:
  port: 9090
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  profiles: itba
elastic:
  baseUrl: http://localhost:9200/jdbc/jdbc
---
server:
  port: 8080
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  profiles: local
elastic:
  baseUrl: http://localhost:9200/jdbc/jdbc
