server:
  port: 9090
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  profiles: itba
elastic:
  baseUrl: http://localhost:9200/jdbc/jdbc
  googleLogo: http://www.google.com/images/branding/product/ico/googleg_lodp.ico
---
server:
  port: 8080
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  profiles: local
elastic:
  baseUrl: http://localhost:9200/jdbc/jdbc
  googleLogo: http://www.google.com/images/branding/product/ico/googleg_lodp.ico
