server:
  port: 8080
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-107-21-101-67.compute-1.amazonaws.com:5432/d2flqi8hpn6nlj?user=kljiyxzimkcype&password=-KTutQDsB-jW-J2AjkuPglMfsw&sslmode=require
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
