server:
  port: 9090
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  profiles: itba
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/politica
    username: bigdatanow
    password: bigdatanow
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
elastic:
  baseUrl: http://localhost:9200/jdbc/jdbc
---
server:
  port: 8080
  context-path: /news-visualization/api
endpoints:
  health:
    sensitive: false
spring:
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/juanjosemarinelli
    username: bigdatanow
    password:
  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
elastic:
  baseUrl: http://localhost:9200/jdbc/jdbc
